print("Charie Ann Logatoc Mascarenas")
print("Ino, Mogpog, Marinduque")
print("April 27,2002")
print("Marinduque State College")
print("BSI/T")
print("2A")
print("Painting")
print("Video & Photo Editing")
print("Singing")
print("Reading")
print("Cycling")